model_path: pretrained_model/fudoki
pretrain_model_path: /cache/xyf_model/
text_embedding_path: /cache/models/LucasJinWang-FUDOKI/text_embedding.pt

stage: s2
txt_max_length: 500
new_embedding_path: ""

pretrain_path: ""
ckpt_path: ""
train_llm_emb: false

data_list: [
  "path/to/nuscenes_train.jsonl",
]

mixed_precision: "no" 
accumulate_grad_batches: 1
max_grad_norm: 1.0
seed: 42
source_distribution: "uniform"
vocab_size: 102400
batch_size: 1
dataloader_num_workers: 8
learning_rate: 5e-6
lr_scheduler_type: "cosine"   # "constant", "cosine"
lr_warmup_steps: 100
max_train_steps: 10000
max_epochs: 100
uncond_prob: 0
use_quantize: true
random_seed: false
l2_loss_weight: 0

checkpointing_steps: 1000
checkpoints_total_limit: 50